Scan photos of specific directory
nextcloud/maps pull request #1231
Opened 2024-03-27 02:41 UTC by tetebueno

I've been getting memory exhaustion when scanning all photos collection; trying to address #525 I made these changes and was able to scan each year/month directory of photos as an initial scan succesfully like this (the example is for the folder with photos of july '84):

```console
$ docker exec -t -u www-data container-name php occ maps:scan-photos -vvv username Photos/1984/06
```

I didn't like the `if`s all over the implementation, but it's something like a _make it work_ approach. If I can get comments about it, we can make it better.

2024-03-27 17:54 UTC, tacruc commented
Thanks for your contribution. Can you pass the path as optional argument?
Do you need help to fix the DCO?

2024-03-28 01:11 UTC, tetebueno commented
You are very welcome.

Done with DCO, thanks.

Is there anything else besides [this](https://github.com/nextcloud/maps/pull/1231/files#diff-1e9219122ae9190e4bb16b6f373272412fdbb5d599ba78bd7480c5672ae45aa8R62) so the path parameter is optional? I believe it already is since help command displays it like this: `... [<user_id> [<path>]]`.

2024-04-21 16:15 UTC, tacruc requested changes
Hi @tetebueno,
sorry for the late reply and beeing a little unprecise.
I mean in stead of adding the functions
RescanPhotos->scanUserPhotos
and
PhotofilesService->rescanPath

Just provide an optional parameter to
```suggestion
       private function rescanUserPhotos(string $userId, bool $inBackground=true, sting? $pathToScan===null) {
```
and PhotofilesService
`public function rescan($userId, $inBackground=true, $pathToScan=null) {`


and then make an if in the Photofilesservice->rescan

```
$userFolder = $this->root->getUserFolder($userId)
if ($pathToScan === null) {
          $folder = $userFolder
} else {
          $folder = $userFolder->get($pathToScan);
}
$photos = $this->gatherPhotoFiles($folder, true);
```

Don't blindly copy my code. It is just typed in here to outline my thought and not tested.

2024-04-21 16:15 UTC, tacruc commented on lib/Command/RescanPhotos.php
> +                if ($pathToScan === null) {
```suggestion
                $this->rescanUserPhotos($user->getUID(), $inBackground, pathToScan);
```

2024-04-21 16:15 UTC, tacruc commented on lib/Command/RescanPhotos.php
> +                }
```suggestion
                $this->rescanUserPhotos($userId, $inBackground, pathToScan);
```

2024-04-21 19:18 UTC, tacruc commented
@tetebueno Do you think you will make the changes befor the NC29 release. Then I would wait with https://github.com/nextcloud/maps/pull/1244 to include this.

I'm sorry that it is on such short notice after not reviewing for a month. Just have to decide whether to wait or not.

2024-11-22 15:52 UTC, marlemion commented
I just wanted to bring this back to mind. In my case it is tedious to update ~100000 Pictures just to get some recently geotagged pictures into Maps....

2024-11-22 19:11 UTC, tetebueno commented
Apologies to everyone. Totally forgot about this.

@tacruc, I'm not completely sure what does this line do in `RescanPhotos+rescanUserPhotos()`, but I tried to maintain the logic intended in the first PR version:
```php
$this->config->setUserValue($userId, 'maps', 'installScanDone', 'yes');
```

2024-11-22 19:11 UTC, tetebueno commented on lib/Command/RescanPhotos.php
> +                if ($pathToScan === null) {
Already applied in last commit.

2024-11-22 20:25 UTC, tetebueno commented
Forgot DCO again and it seems I went too far with it double-signing-off everything.

2024-11-24 00:26 UTC, tetebueno commented
Ok, my bad, tried merging with Github's visual tool and it was an indentation mess ~~challenge~~. Will take care of this as soon as I can.

2024-12-11 03:08 UTC, tetebueno commented
Finally got some time to pull this to a local environment and merge and fix formatting issues. Hope this is it.

2024-12-21 20:56 UTC, tacruc approved these changes

2024-12-21 21:00 UTC, tacruc commented
@tetebueno  Thanks alot for your contribution. I will see if I find time the next two weeks to publish them. But I cannot promise it.

2024-12-21 21:00 UTC, merged

2024-12-21 21:06 UTC, tetebueno commented
Gaaa, just got a chance to run `composer run cs:fix` and pushed the fixed code. Thanks anyway. I'm available for any issues regarding this.